/**
 * Generates src/icons/registry.ts from @tabler/icons-react exports.
 *
 * Run: bun run tsx scripts/generate-registry.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";

// Import all icon exports from @tabler/icons-react
// biome-ignore lint: dynamic require for script
const icons = require("@tabler/icons-react");

// Load Tabler icon metadata (tags, categories) for enhanced search
const tablerMetaPath = path.resolve(
  __dirname,
  "../node_modules/@tabler/icons/icons.json",
);
const tablerMeta: Record<
  string,
  { name: string; category: string; tags: (string | number)[] }
> = JSON.parse(fs.readFileSync(tablerMetaPath, "utf-8"));

// Known animated icons -- update this list as new animated icons are created
const ANIMATED_ICONS = new Set([
  "activity",
  "alarm",
  "alert-triangle",
  "anchor",
  "archive",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "bell",
  "bolt",
  "bookmark",
  "calendar",
  "camera",
  "chart-bar",
  "chart-line",
  "check",
  "circle-check",
  "clipboard",
  "clock",
  "cloud",
  "code",
  "coffee",
  "compass",
  "confetti",
  "copy",
  "cpu",
  "credit-card",
  "crown",
  "currency-dollar",
  "database",
  "device-desktop",
  "device-mobile",
  "download",
  "edit",
  "eye",
  "file",
  "flag",
  "flame",
  "folder",
  "gift",
  "globe",
  "heart",
  "help-circle",
  "home",
  "inbox",
  "info-circle",
  "key",
  "layout",
  "link",
  "list",
  "loader",
  "lock",
  "logout",
  "mail",
  "map-pin",
  "menu",
  "message",
  "microphone",
  "minus",
  "moon",
  "music",
  "palette",
  "pencil",
  "phone",
  "photo",
  "pin",
  "plug",
  "plus",
  "power",
  "printer",
  "puzzle",
  "refresh",
  "rocket",
  "scissors",
  "search",
  "send",
  "server",
  "settings",
  "share",
  "shield",
  "sparkles",
  "star",
  "sun",
  "tag",
  "target",
  "terminal",
  "trash",
  "trophy",
  "upload",
  "user",
  "users",
  "video",
  "volume",
  "wand",
  "wifi",
  "world",
  "x",
  "zoom-in",
  "zoom-out",
]);

function componentNameToSlug(componentName: string): string {
  // Remove "Icon" prefix, then convert PascalCase to kebab-case
  const withoutPrefix = componentName.replace(/^Icon/, "");
  return withoutPrefix
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

function generateKeywords(name: string): string[] {
  // Split the slug on hyphens for keywords
  const parts = name.split("-").filter(Boolean);
  return [...new Set([name, ...parts])];
}

function getTablerMeta(name: string): {
  tags: string[];
  category: string;
} {
  const meta = tablerMeta[name];
  if (!meta) return { tags: [], category: "" };
  // Tabler tags can contain numbers, coerce to strings
  const tags = meta.tags.map(String);
  return { tags, category: meta.category };
}

type IconEntry = {
  name: string;
  componentName: string;
  keywords: string[];
  tags: string[];
  category: string;
  animated: boolean;
};

function main() {
  const allExports = Object.keys(icons);

  // Filter for outline icons only (no "Filled" suffix), must start with "Icon"
  const iconComponents = allExports.filter(
    (key) =>
      key.startsWith("Icon") &&
      key !== "Icon" &&
      !key.endsWith("Filled") &&
      icons[key] != null,
  );

  // Sort alphabetically
  iconComponents.sort();

  const entries: IconEntry[] = iconComponents.map((componentName) => {
    const name = componentNameToSlug(componentName);
    const { tags, category } = getTablerMeta(name);
    return {
      name,
      componentName,
      keywords: generateKeywords(name),
      tags,
      category,
      animated: ANIMATED_ICONS.has(name),
    };
  });

  // Generate the TypeScript file
  const output = `// Auto-generated by scripts/generate-registry.ts
// Do not edit manually. Run: bun run tsx scripts/generate-registry.ts

export type IconEntry = {
  name: string;
  componentName: string;
  keywords: string[];
  tags: string[];
  category: string;
  animated: boolean;
};

export const iconRegistry: IconEntry[] = ${JSON.stringify(entries, null, 2)};

export const iconMap = new Map<string, IconEntry>(
  iconRegistry.map((entry) => [entry.name, entry]),
);

export const animatedIcons = iconRegistry.filter((entry) => entry.animated);

export const totalIcons = iconRegistry.length;
export const totalAnimated = animatedIcons.length;
`;

  const outPath = path.resolve(__dirname, "../src/icons/registry.ts");
  fs.writeFileSync(outPath, output, "utf-8");

  console.log(`Generated registry with ${entries.length} icons`);
  console.log(`Animated: ${entries.filter((e) => e.animated).length}`);
  console.log(`Written to: ${outPath}`);
}

main();
