/**
 * Generates src/icons/registry.ts from @tabler/icons-react exports.
 *
 * Run: bun run tsx scripts/generate-registry.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";

// Import all icon exports from @tabler/icons-react
// biome-ignore lint: dynamic require for script
const icons = require("@tabler/icons-react");

// Load Tabler icon metadata (tags, categories) for enhanced search
const tablerMetaPath = path.resolve(
  __dirname,
  "../node_modules/@tabler/icons/icons.json",
);
const tablerMeta: Record<
  string,
  { name: string; category: string; tags: (string | number)[] }
> = JSON.parse(fs.readFileSync(tablerMetaPath, "utf-8"));

// Known animated icons -- update this list as new animated icons are created
const ANIMATED_ICONS = new Set([
  "a-arrow-down",
  "a-arrow-up",
  "accessibility",
  "activity",
  "air-vent",
  "airplane",
  "airplay",
  "alarm-clock",
  "align-center",
  "align-horizontal",
  "align-left",
  "align-right",
  "align-vertical",
  "archive",
  "arrow-big-down-dash",
  "arrow-big-down",
  "arrow-big-left-dash",
  "arrow-big-left",
  "arrow-big-right-dash",
  "arrow-big-right",
  "arrow-big-up-dash",
  "arrow-big-up",
  "arrow-down-0-1",
  "arrow-down-1-0",
  "arrow-down-a-z",
  "arrow-down-left",
  "arrow-down-right",
  "arrow-down-z-a",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up-left",
  "arrow-up-right",
  "arrow-up",
  "at-sign",
  "atom",
  "attach-file",
  "audio-lines",
  "badge-percent",
  "ban",
  "banana",
  "battery-charging",
  "battery-plus",
  "battery-warning",
  "battery",
  "bell",
  "blocks",
  "bluetooth-connected",
  "bluetooth-off",
  "bluetooth-searching",
  "bluetooth",
  "bold",
  "bone",
  "bookmark-check",
  "bookmark-minus",
  "bookmark-plus",
  "bookmark-x",
  "bookmark",
  "bot",
  "box",
  "boxes",
  "calendar-check-2",
  "calendar-check",
  "calendar-cog",
  "calendar-days",
  "cast",
  "cctv",
  "chart-bar-decreasing",
  "chart-bar-increasing",
  "chart-column-decreasing",
  "chart-column-increasing",
  "chart-line",
  "chart-no-axes-column-decreasing",
  "chart-no-axes-column-increasing",
  "chart-pie",
  "chart-spline",
  "check-check",
  "check",
  "chevron-down",
  "chevron-first",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "chevrons-down-up",
  "chevrons-left-right",
  "chevrons-right-left",
  "chevrons-up-down",
  "chrome",
  "circle-check",
  "circle-chevron-down",
  "circle-chevron-left",
  "circle-chevron-right",
  "circle-chevron-up",
  "circle-dashed",
  "circle-dollar-sign",
  "circle-help",
  "clap",
  "clipboard-check",
  "clock",
  "cloud-cog",
  "cloud-download",
  "cloud-lightning",
  "cloud-rain-wind",
  "cloud-rain",
  "cloud-snow",
  "cloud-sun",
  "cloud-upload",
  "coffee",
  "compass",
  "connect",
  "construction",
  "contrast",
  "cooking-pot",
  "copy",
  "cpu",
  "cursor-click",
  "delete",
  "discord",
  "dollar-sign",
  "download",
  "dribbble",
  "droplet",
  "drum",
  "earth",
  "euro",
  "ev-charger",
  "expand",
  "eye-off",
  "eye",
  "facebook",
  "heart",
  "home",
  "menu",
  "moon",
  "search",
  "settings",
  "star",
  "sun",
  "trash",
  "user",
]);

function componentNameToSlug(componentName: string): string {
  // Remove "Icon" prefix, then convert PascalCase to kebab-case
  const withoutPrefix = componentName.replace(/^Icon/, "");
  return withoutPrefix
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

function generateKeywords(name: string): string[] {
  // Split the slug on hyphens for keywords
  const parts = name.split("-").filter(Boolean);
  return [...new Set([name, ...parts])];
}

function getTablerMeta(name: string): {
  tags: string[];
  category: string;
} {
  const meta = tablerMeta[name];
  if (!meta) return { tags: [], category: "" };
  // Tabler tags can contain numbers, coerce to strings
  const tags = meta.tags.map(String);
  return { tags, category: meta.category };
}

type IconEntry = {
  name: string;
  componentName: string;
  keywords: string[];
  tags: string[];
  category: string;
  animated: boolean;
};

function main() {
  const allExports = Object.keys(icons);

  // Filter for outline icons only (no "Filled" suffix), must start with "Icon"
  const iconComponents = allExports.filter(
    (key) =>
      key.startsWith("Icon") &&
      key !== "Icon" &&
      !key.endsWith("Filled") &&
      icons[key] != null,
  );

  // Sort alphabetically
  iconComponents.sort();

  const entries: IconEntry[] = iconComponents.map((componentName) => {
    const name = componentNameToSlug(componentName);
    const { tags, category } = getTablerMeta(name);
    return {
      name,
      componentName,
      keywords: generateKeywords(name),
      tags,
      category,
      animated: ANIMATED_ICONS.has(name),
    };
  });

  // Generate the TypeScript file
  const output = `// Auto-generated by scripts/generate-registry.ts
// Do not edit manually. Run: bun run tsx scripts/generate-registry.ts

export type IconEntry = {
  name: string;
  componentName: string;
  keywords: string[];
  tags: string[];
  category: string;
  animated: boolean;
};

export const iconRegistry: IconEntry[] = ${JSON.stringify(entries, null, 2)};

export const iconMap = new Map<string, IconEntry>(
  iconRegistry.map((entry) => [entry.name, entry]),
);

export const animatedIcons = iconRegistry.filter((entry) => entry.animated);

export const totalIcons = iconRegistry.length;
export const totalAnimated = animatedIcons.length;
`;

  const outPath = path.resolve(__dirname, "../src/icons/registry.ts");
  fs.writeFileSync(outPath, output, "utf-8");

  console.log(`Generated registry with ${entries.length} icons`);
  console.log(`Animated: ${entries.filter((e) => e.animated).length}`);
  console.log(`Written to: ${outPath}`);
}

main();
